### ISSUE TITLE
Alibaba: upload to OSS bucket fails after a while

### ISSUE THREAD

**Issue by amolari** [f5devcentral/f5-bigip-image-generator#31]
**Describe the bug**
The upload process to alibaba OSS bucket doesn't work.

File starts to upload (I can see the parts in the OSS console) and after a while, we get an error.

In generator log:
```
2021-11-09 22:22:28 image-generator DEBUG - Extracting '.qcow2 disk file from [/root/f5-bigip-image-generator-1.15/src/lib/bash/../../../artifacts/BIGIP-14.1.4.4-0.0.4/alibaba/all_2slot/staging/Hotfix-BIGIP-14.1.4.4-0.27.4.ALL.alibaba.tar.gz].
2021-11-09 22:23:22 image-generator INFO - Alibaba disk_to_upload = '/root/f5-bigip-image-generator-1.15/src/lib/bash/../../../artifacts/BIGIP-14.1.4.4-0.0.4/alibaba/all_2slot/image_alibaba_a_c3zp7b/Hotfix-BIGIP-14.1.4.4-0.27.4.ALL.alibaba.qcow2'
2021-11-09 22:23:23 image-generator INFO - Upload iteration number 1
2021-11-09 22:23:23 image-generator INFO - Uploading /root/f5-bigip-image-generator-1.15/src/lib/bash/../../../artifacts/BIGIP-14.1.4.4-0.0.4/alibaba/all_2slot/image_alibaba_a_c3zp7b/Hotfix-BIGIP-14.1.4.4-0.27.4.ALL.alibaba.qcow2 as bakery-Hotfix-BIGIP-14.1.4.4-0.27.4.ALL.alibaba.qcow2-974218
2021-11-09 22:37:40 image-generator ERROR - {'status': 403, 'x-oss-request-id': '', 'details': {}}
Traceback (most recent call last):
  File "/root/f5-bigip-image-generator-1.15/src/lib/python/image/image_controller.py", line 161, in prepare
    self.cloud_image.upload_disk()
  File "/root/f5-bigip-image-generator-1.15/src/lib/python/image/alibaba_image.py", line 50, in upload_disk
    self.disk.upload()
  File "/root/f5-bigip-image-generator-1.15/src/lib/python/image/alibaba_disk.py", line 96, in upload
    if retrier.execute():
  File "/root/f5-bigip-image-generator-1.15/src/lib/python/util/retrier.py", line 80, in execute
    if _execute():
  File "/root/f5-bigip-image-generator-1.15/.venv/lib/python3.6/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/f5-bigip-image-generator-1.15/.venv/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/root/f5-bigip-image-generator-1.15/.venv/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/root/f5-bigip-image-generator-1.15/src/lib/python/util/retrier.py", line 71, in _execute
    if self.func(*self.args, **self.kwargs):
  File "/root/f5-bigip-image-generator-1.15/src/lib/python/image/alibaba_disk.py", line 76, in _resumable_upload
    store=resumable_store, num_threads=number_of_threads)
  File "/root/f5-bigip-image-generator-1.15/.venv/lib/python3.6/site-packages/oss2/resumable.py", line 94, in resumable_upload
    result = uploader.upload()
  File "/root/f5-bigip-image-generator-1.15/.venv/lib/python3.6/site-packages/oss2/resumable.py", line 586, in upload
    q.run()
  File "/root/f5-bigip-image-generator-1.15/.venv/lib/python3.6/site-packages/oss2/task_queue.py", line 44, in run
    raise self.__exc_info[1]
  File "/root/f5-bigip-image-generator-1.15/.venv/lib/python3.6/site-packages/oss2/task_queue.py", line 76, in __consumer_func
    consumer(self)
  File "/root/f5-bigip-image-generator-1.15/.venv/lib/python3.6/site-packages/oss2/resumable.py", line 606, in __consumer
    self.__upload_part(part)
  File "/root/f5-bigip-image-generator-1.15/.venv/lib/python3.6/site-packages/oss2/resumable.py", line 620, in __upload_part
    utils.SizedFileAdapter(f, part.size), headers=headers)
  File "/root/f5-bigip-image-generator-1.15/.venv/lib/python3.6/site-packages/oss2/api.py", line 1323, in upload_part
    data=data)
  File "/root/f5-bigip-image-generator-1.15/.venv/lib/python3.6/site-packages/oss2/api.py", line 2529, in __do_object
    return self._do(method, self.bucket_name, key, **kwargs)
  File "/root/f5-bigip-image-generator-1.15/.venv/lib/python3.6/site-packages/oss2/api.py", line 231, in _do
    raise e
oss2.exceptions.ServerError: {'status': 403, 'x-oss-request-id': '', 'details': {}}
2021-11-09 22:37:40 image-generator INFO - Cleaning up image controller constructs.
2021-11-09 22:37:40 image-generator INFO - Cleaning-up AlibabaImage artifacts.
2021-11-09 22:37:40 image-generator DEBUG - Deleting the local disk that was (or had to be) uploaded:= '/root/f5-bigip-image-generator-1.15/src/lib/bash/../../../artifacts/BIGIP-14.1.4.4-0.0.4/alibaba/all_2slot/image_alibaba_a_c3zp7b/Hotfix-BIGIP-14.1.4.4-0.27.4.ALL.alibaba.qcow2'
2021-11-09 22:37:40 image-generator DEBUG - Cleaning up the uploaded disk from Alibaba storage
2021-11-09 22:37:40 image-generator INFO - Storage file bakery-Hotfix-BIGIP-14.1.4.4-0.27.4.ALL.alibaba.qcow2-974218 does not exist, no need to delete it
2021-11-09 22:37:41 image-generator INFO - Found fragments for file bakery-Hotfix-BIGIP-14.1.4.4-0.27.4.ALL.alibaba.qcow2-974218 upload id 549FB25058F540D585798F84D02D724C, deleting them
2021-11-09 22:37:41 image-generator INFO - Completed AlibabaImage clean-up.
```

**To Reproduce**
v1.15

**Expected behavior**
File is fully uploaded

**Additional context**
We go through a webproxy.
Upload of the same file with ossutil tool and the oss2 sdk do work from the same machine (proxy used, same network conditions), with same credentials.
Uploading the oss2 python module from 2.14.0 to 2.15.0 doesn't help.

**Comment by amolari** [comment]
It would be good, that if we set LOG_LEVEL=DEBUG, then the logging level is also set to the same level in the called modules (oss2). That would help a lot for troubleshooting

**Comment by amolari** [comment]
Issue was my side -> webproxy (blocking some part upload), closing.
