### ISSUE TITLE
Key [AZURE_TENANT_ID] is required for platform [azure]!

### ISSUE THREAD

**Issue by DahlPatric** [f5devcentral/f5-bigip-image-generator#43]
**Describe the bug**
Asking for **Key [AZURE_TENANT_ID]** is required for platform [azure]! followed with File errors.

**To Reproduce**
**./build-image -i ~/images/BIGIP-16.1.3.3-0.0.3.iso -p azure -m all -b 2**
Set check_setup_json_dir:/home/patric/f5-bigip-image-generator
Initializing global variable definitions
CONFIG_FILE not set
Initializing variable definitions for platform [azure]
Parsing remaining command line arguments
Assigning default values to eligible variables
Validating that required variables are present
**Key [AZURE_TENANT_ID] is required for platform [azure]!**
Please run with -h flag for detailed help
Traceback (most recent call last):
  File "/home/patric/f5-bigip-image-generator/src/bin/output_config.py", line 49, in <module>
    main()
  File "/home/patric/f5-bigip-image-generator/src/bin/output_config.py", line 35, in main
    create_log_handler()
  File "/home/patric/f5-bigip-image-generator/src/lib/python/util/misc.py", line 195, in create_log_handler
    create_file_handler(LOGGER, log_file, log_level)
  File "/home/patric/f5-bigip-image-generator/src/lib/python/util/logger.py", line 79, in create_file_handler
    f_h = logging.FileHandler(path, mode, encoding='utf-8')
  File "/usr/lib/python3.8/logging/__init__.py", line 1134, in __init__
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Expected behavior**

**Additional context**

**Comment by gabetellier** [comment]
Hi,
Unfortunately, this tool has reached end of software development and end of technical support. F5 will not fix this issue.
